services:
  rsl_travel:
    extends:
      file: docker-compose-gui.yaml
      service: rsl_travel
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia